[build]
  base = "frontend"
  command = "npm run build"
  publish = "dist/spa"

[[plugins]]
  package = "@netlify/build"
  [plugins.inputs]
    command = "npm install -g @quasar/cli && npm run build"

[build.environment]
  NODE_VERSION = "22.17.0"
